---
title: Et on démarre
author: Fousseynou Bah
date: '2018-05-03'
categories:
  - Introduction
  - R
tags:
  - QGIS
  - R
  - Rmarkdown
  - Ubuntu
slug: here-i-go
---

Pendant que j'écris ces mots, je suis terrifié.
Pas parce que j'ai été sommé par la Reine Cersei ou parce que je livre une bataille aux Marcheurs Blancs aux côtés de Jon Snow.
Non.
J'aurais bien voulu.
Ok, presque.
Je suis terrifié parce que ceci est mon premier pas dans le *blogging*.
Il y a quelques années, quand j'étais plus jeune, j'aurai probablement été serein.
Mais maintenant, maintenant que je connais le poids des mots, j'ai tendance à être prudent quand je parle ou j'écris.
Une fois que c'est sorti, c'est sorti.
Mais bon...celà n'est pas une excuse.

Il y a quelques mois, j'ai décidé de tester les eaux avec R.
Jusqu'à ce point, j'utilisais [Stata](https://www.stata.com/).
Nous avions une relation solide, mais quelque part une distance s'est creusée entre nous.
Stata avait des versions nouvelles, plus fortes et meilleures qui sortaient pendant que moi je continuais d'utiliser la version que j'avais acquise pendant mes études universitaires (fin des années 2000!).
En vérité, je suis resté derrière.
Enfin, pas entièrement.
J'ai commencé à avoir des "sentiments" forts pour l'*open-source*.
Entre ma première rencontre avec Stata et notre rupture, j'ai découvert les joies (et parfois les tribulations) des programmes et systèmes open-source.
Mon coeur continue de battre pour [Ubuntu](https://www.ubuntu.com/), mais pour des raisons pratiques (travaillant dans un environnement dominé par Windows), je dois reporter nos retrouvailles.
On se retrouvera un jour.
Un beau jour, _One Sweet Day_ comme le dit [cette chanson](https://www.youtube.com/watch?v=UXxRyNvTPr8).
J'ai aussi aimé mon temps avec [QGIS](https://qgis.org/en/site/).
Pendant quelque temps, il m'a donné le sentiment d'être un Maître, un Maître des Cartes.
Malheureusement, en dehors des projets où il me fallait des cartes, nous ne trainions pas trop ensemble (après tout, les cartes sont tout ce qu'il peut faire).
Aussi, je trouverais difficile de naviguer entre différents programmes (Stata par-ci, QGIS par-là, une base de donnée là...).
Avec le temps, la distance entre nous n'a fait que grandir.
Une chose quand même.
Je suis à blâmer, partiellement.
Je ne me suis pas donné la peine d'apprendre SQL pour sauter le *middle man* (dans ce cas précis, Stata), pour acceder à mes bases de données depuis QGIS.
Enfin bref....de l'eau sous le pont.

Mes relations avec ces outils ont connu leurs hauts et leurs bas [comme Ross et Rachel](https://www.youtube.com/watch?v=DQuAsShq68Q).
Bien sûr, j'ai eu mon lot de nuits sans sommeil, essayant de comprendre pourquoi mon système marchait de façon étrange, essayant de prendre  la main sur un document créé sous un autre système ou dans un autre programme (imaginez MsOffice versus LibreOffice).
Mais, de façon générale, j'ai eu un aperçu des possibilités qui restent à venir.
Avec la sortie de nouvelles versions sur une base régulière, la vitesse à laquelle les *bugs* sont corrigés, il semble que l'open-source se dresse parmi et restera parmi les forces de l'innovation technologique ( [Thomas Friedman de New York times écrit à propos de ces choses de façon tellement éloquente. Plus que je ne saurai. Allez le lire!](https://www.nytimes.com/column/thomas-l-friedman)).
Aussi, beaucoup de ces programmes et systèmes sont gratuis!
Et ceci est une raison pratique qui l'emporte sur toutes les autres raisons.

Revenons-en à R.
L'année dernière, j'ai eu un moment de...d'épiphanie.
Considérant tout le passé que j'ai partagé avec Stata, les histoires brèves que j'ai eues avec Ubuntu et QGIS, et le futur prometeur que je vois dan l'open-source (ok, l'aspect *gratuit* a joué un grand rôle, je l'admets), j'ai décidé de faire le saut, d'apprendre R.
Ceci signifiait réécrire d'inombrables lignes de codes, des scripts qu'il m'a pris des années à écrire.
Mais, de façon plus importante, ceci impliquait d'apprendre un nouveau langage, de comprendre un nouvel environnement.
J'ai été en ligne pour trouver quelques tutoriels.
J'en ai trouvé beaucoup, gratuitement, mais je n'ai pas eu une structure, une méthodologie pour faciliter mon accès à R et m'accompagner dans mon apprentissage. 
Et j'ai découvert [DataCamp](http://datacamp.com/) (permettez-moi de dire ceci dès à présent: ils ne me payent pas pour dire ça!).
Je l'ai essayé, j'ai aimé et j'ai adopté.
En quelques mois, je complété un cursus dense, *Data Science with R*.
Ensuite, j'ai pris une pause pendant quelques semaines, pour ensuite commencer un autre, *Quantitative Analyst with R*.
Je suis encore là dessus.
De tant à autre, j'essaie de nouveaux cours en dehors de mon cursus (ce n'est pas ce que ça a l'air d'être, ça ne signifie rien du tout! A peine je me rapelle leurs noms!)


Toute cette expérience m'a ouvert les yeux.
Tout ce que je me dis, c'est "pourquoi n'ai-je pas commencé plus tôt?"
Et pourtant, j'aurai pu car j'ai eu des cours sur R pendant mes études supérieures.
Je ne me suis pas donné la peine d'aller à ces cours parce que je ne pensais pas que les sauter me pénaliserait tant que ça en matière de notes (et ça m'a pénalisé!), ou que dans le futur je travaillerai comme analyste de données (contraitement au grand Professeur d'Economie International que j'espérais devenir.)
Enfin bref...mieux vaut tard que jamais.
N'est-ce pas?
J'ai trouvé dans R un espace où j'aimerai demeurer pour longtemps, très longtemps.
Et, en toute honnêteté, [RStudio](https://www.rstudio.org/) y est pour une grande part (Rstudio ne me paie pas pour dire ça hein!).
En restant dans un seul environnement, je peux faire beaucoup de choses, écrire de nouveaux codes, traduire mes anciens codes (de jours de Stata - imaginez si vous devez récupérer des affaires à vous dans l'apparment de votre ex. Bizarre!), créer des graphiques ou cartes spectaculaires avec ggplot2 (désolé QGIS, R fait vraiment tout ce dont j'ai besoin), écrire des rapports et articles avec Latex (Texmaker, nous étions bon ensemble. N'est-ce pas?).
Et celà est tout simplement génial.

Et maintenant, ce blog.
Mon adoption de R est venue avec (et est partie de) un désir de vivre et même de faire partie de ce qui rend notre pérode de l'histoire particulière (enfin, à votre humble avis).
Et ça, c'est la façon dont la connectivité nous rend capable de partager, de collaborer et de travailler collectivement.
Et ceci est une immense opportunité (pour moi, mais je suppose pour beaucoup d'autres comme moi), une dont je commence seulement à prendre la mesure.
Je suis un Africain, né, élevé et vivant en Afrique.
Faisant partie de ce monde, où les obstacles à surmonter sont inombrables, la connectivité semble offrir l'une des voies les plus prometteuse pour un meilleur lendemain.
J'ai pu acquérir de nouvelles compétences sans avoir besoin de mettre ma vie en attente, sans avoir à voyager vers l'Occident pour aller à une prestigieuse université (celà dit, je n'hésiterai pas du tout à le faire).
J'ai juste eu à me connecter et à trouver ce que je cherchais.
Donc j'ai décidé de rester en ligne, de partager mon expérience et de commence de nouveaux projets sur lesquels, j'espère, je pourrai collaborer avec d'autres personnes.
J'ai aussi commencé de blog parce que, vivant dans ce siècle, dans ce monde incessament globalisé et digitalisé, rester à la marge n'est pas un choix, mais une sentence.
La vitesse du progrès technologique est telle qu'on ne peut se permettre de décrocher pour longtemps.
Et heureusement, on a plus à décrocher.
Enfin, avec ce blog, je tente de surmonter mes peurs.
J'ai eu la chance d'avoir été impliqué dans divers projets.
Et, quelque fois, j'ai la folle idée d'en initier quelques unes à moi-même.
Et maintenant, je réalise que j'ai l'opportunité de les dépoussiérer et de les partager avec d'autres personnes à qui ils pourraient servir.