---
title: Probably over my head
author: Fousseynou Bah
date: '2018-05-04'
categories:
  - R
tags:
  - data
  - Mali
  - R Markdown
  - security
  - terrorism
  - threats
slug: probably-over-my-head
---

Last year, I made a new friend.
She (yes, it's a "she") introduced me to Kaggle.
I had no idea what that was.
She was amused, and I slightly embarrassed.
I, who think of myself as a worldly man, modern, aware of what happening here and there (yes, I get sometimes caught up a delusion of grandeur in my head), had no clue what Kaggle was.
She proposed that we train together to enter a competition.
I saw an opportunity to bond.
So, I said yes.
Come one, you'd do the same.
She knew how to use R, I was a Stata man.
This was going to be a Romeo-and-Juliette situation (you know...outside forces keeping us apart...ok, I just want to draw a shamelessly impertinent parallel) unless I did something about it.
I decided to learn R.
I know I told the story of my transition to R as the result of an "epiphany", and I still stand by that.
I just hadn't told what triggered the "epiphany".
Now, you know.

Just few weeks after our first encounter, I had finished my first track on DataCamp, "Data Scientist with R".
It was quite a ride.
I didn't get everything right away, but I knew that practice was the key to becoming a skilled data scientist.
I knew I just had to keep going.
I had a support system, my friend, and a goal, a Kaggle competition.

Flash forward.
My friend and I still haven't entered that competition because we are living on different continents.
Ok, that's no excuse.
Sure, we bonded over other things. 
She made me like Simon & Garfunkel (I myself am still shocked) and, I shared with her my passion for Pop Rock from the 1980's and R'n'B from the 1990's).
Sadly, somewhere along the way, R became more mine than hers.
And, that's ok.
We still have the Sound of Silence (don't say anything, I'm more shocked than you).

One advice I took away from most of the websites I visited, videos I watched on Youtube, and documents I read was the need to practice, and, preferably, on projects that hold a particular interest for the one who's learning.
Therefore, I started to look for a topic what would speak to my interest, not just data to practice on.
And I found something interesting, challenging, and, possibly, over my head.
It was the security threats in my home country, Mali.
I found out that a website, [Malilink](http://malilink.net/attaques-terroriste-au-mali/), keeps a list on the incidents (terrorist attacks, clashes between communities, etc.) that have occurred since 2015.
I knew about the website, but not that particular page.
And, honestly, without the training in R, I would not have thought much of it, expect to bring it up in conversations with friends.
But the new me (the 2.0 me) saw more (you know, like Sherlock Holmes).

At first, I thought to myself that this topic was too sensitive.
We were and are still dealing with those threats.
People are dying, communities are being unraveled, and, at times, it feels like everything can collapse.
I didn't want to contribute to that with my uneducated opinions.
That's the truth: I don't know much about geopolitics or terrorism.
But I knew, that I could do something with the information I found, and I didn't want to keep it to myself.
If the folks behind the website had done the same, I wouldn't have had a project in the first place.
I also told myself that if I was going to use any data from the website, I had the moral obligation to share the results.
I cannot claim that the list on the website is accurate, reliable or exhaustive, but there is one thing that deserves credit: the contributors went public with their information, giving anybody the chance to challenge it.
And that's one reason why I took a chance on it.

Another reason why I kept my sight on this topic was the technical challenge the data presented.
They were not organized in the sense of readiness for analysis.
They were not "tidy".
So, they offered me the opportunity to train in data wrangling.
And I was optimistic about my chances in that battle (Happy Potter had his wand and the smarts of Hermione against Voldomort, I had the packages of tidyverse against my "list").

A final reason is the need I felt to contribute to the documentation of our history.
No matter what one thinks as to the causes of our current predicament, or who they think is responsible for it, one thing is sure: what we are going through needs to be documented in all the possible ways.
Sure news articles are coming out everyday, and books are being written.
But I haven't run into many statistics on the human losses we have been suffering over the last seven years.
The numbers are chilling.
I had to undertake this project to see that.